services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: restro_booker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: bash /workspace/scripts/start-dev.sh
    #command: sh -c "ls -l /workspace/scripts && chmod +x /workspace/scripts/start-dev.sh && /workspace/scripts/start-dev.sh"
    ports:
      - "3000:3000"
      - "5173:5173"
      - "5000:5000"
    volumes:
      - ..:/workspace:cached
      - /workspace/node_modules
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/restro_booker
    depends_on:
      - db
volumes:
  pgdata:
